-- Crear base de datos si no existe con codificacion utf8mb4
CREATE DATABASE IF NOT EXISTS blog
CHARACTER SET utf8mb4
COLLATE utf8mb4_general_ci;

-- Usar la base de datos
USE blog;

-- Crear tabla usuarios con codificacion utf8mb4
CREATE TABLE IF NOT EXISTS usuarios (
    id INT AUTO_INCREMENT PRIMARY KEY,
    nombre VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL UNIQUE,
    contrasena VARCHAR(255) NOT NULL,
    creado_en TIMESTAMP DEFAULT CURRENT_TIMESTAMP
) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;

-- Crear tabla publicaciones con codificacion utf8mb4
CREATE TABLE IF NOT EXISTS publicaciones (
    id INT AUTO_INCREMENT PRIMARY KEY,
    titulo VARCHAR(255) NOT NULL,
    contenido TEXT NOT NULL,
    img_url VARCHAR(255),
    autor_id INT,
    creado_en TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (autor_id) REFERENCES usuarios(id)
) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;

-- Insertar datos iniciales en usuarios
INSERT INTO usuarios (nombre, email, contrasena) VALUES ('Admin', 'admin@prueba.com', 'adminpassword');

INSERT INTO publicaciones (`id`,`titulo`,`contenido`,`img_url`,`autor_id`,`creado_en`) VALUES (1,'HTML','HTML es el lenguaje de marcado estandar utilizado para crear y estructurar paginas web. Sirve como la base fundamental de la web, ya que define la estructura y el contenido de una pagina mediante el uso de etiquetas y elementos. Estas etiquetas encapsulan diferentes partes del contenido como texto, imagenes, enlaces, y otros medios, permitiendo que los navegadores web rendericen la pagina de manera adecuada. HTML es un lenguaje declarativo, lo que significa que describe que contenido se muestra y en que orden, pero no especifica como debe verse o comportarse, ya que esto se gestiona por CSS y JavaScript, respectivamente. Con la evolucion hacia HTML5, el lenguaje ha incorporado nuevas capacidades, como soporte para multimedia, graficos mediante <canvas>, y APIs para manipulacion de datos, lo que lo hace mas poderoso y flexible para el desarrollo web moderno.','./img/html5.png',1,'2024-08-12 23:26:34');
INSERT INTO publicaciones (`id`,`titulo`,`contenido`,`img_url`,`autor_id`,`creado_en`) VALUES (2,'CSS','CSS es el lenguaje utilizado para describir la presentacion de un documento escrito en HTML o XML. A traves de CSS, se pueden aplicar estilos a elementos HTML, controlando aspectos como colores, fuentes, tamanos, margenes, espaciados, y la disposicion general del contenido en la pagina. El concepto de cascading en CSS se refiere a la forma en que los estilos se aplican en orden de precedencia, permitiendo a los disenadores combinar multiples estilos de diferentes fuentes y jerarquizar reglas que pueden ser sobrescritas o heredadas. Con el tiempo, CSS ha evolucionado para incluir potentes herramientas de diseno como flexbox, grid, y animaciones, permitiendo a los desarrolladores crear interfaces visualmente ricas y altamente responsivas que se adaptan a diferentes tamanos de pantalla y dispositivos.','./img/css.png',1,'2024-08-21 22:33:34');
INSERT INTO publicaciones (`id`,`titulo`,`contenido`,`img_url`,`autor_id`,`creado_en`) VALUES (3,'Javascript','JavaScript es un lenguaje de programacion dinamico y versatil que se utiliza principalmente para anadir interactividad y funcionalidades avanzadas a las paginas web. A diferencia de HTML y CSS, que definen la estructura y el estilo, JavaScript permite la manipulacion directa del contenido y el comportamiento del DOM (Document Object Model), respondiendo a eventos del usuario, como clics, desplazamientos, y entradas de teclado. Es un lenguaje del lado del cliente, lo que significa que se ejecuta en el navegador del usuario, pero tambien puede usarse en el lado del servidor a traves de plataformas como Node.js. JavaScript es esencial para el desarrollo de aplicaciones web modernas, ya que facilita la creacion de experiencias de usuario dinamicas, como la carga asincrona de datos con AJAX, la validacion de formularios en tiempo real, y la animacion de elementos en la pagina.','./img/javascript.png',1,'2024-08-21 22:33:34');
INSERT INTO publicaciones (`id`,`titulo`,`contenido`,`img_url`,`autor_id`,`creado_en`) VALUES (4,'PHP','PHP es un lenguaje de scripting del lado del servidor que se utiliza ampliamente para el desarrollo web. Permite a los desarrolladores crear paginas web dinamicas y aplicaciones interactuando con bases de datos, manejando formularios, y generando contenido en respuesta a las solicitudes del usuario. PHP se incrusta dentro del HTML, lo que facilita la integracion de logica de programacion directamente en las paginas web. Es especialmente popular en el desarrollo de sistemas de gestion de contenidos (CMS) como WordPress, asi como en aplicaciones de comercio electronico y foros en linea. PHP es conocido por su flexibilidad y su amplia compatibilidad con servidores web y bases de datos, lo que lo convierte en una eleccion frecuente para proyectos web de pequena y mediana escala.','./img/PHP.png',1,'2024-08-21 22:33:34');
INSERT INTO publicaciones (`id`,`titulo`,`contenido`,`img_url`,`autor_id`,`creado_en`) VALUES (5,'MySQL','MySQL es un sistema de gestion de bases de datos relacional (RDBMS) basado en SQL (Structured Query Language). Es una de las bases de datos mas populares para aplicaciones web, y se utiliza para almacenar, gestionar y recuperar datos de manera estructurada y eficiente. MySQL soporta multiples tablas, permite relaciones entre ellas, y ofrece potentes capacidades de consulta, lo que facilita la gestion de grandes volumenes de datos. Es ampliamente utilizado en conjunto con lenguajes de programacion como PHP para construir aplicaciones web dinamicas donde los datos son fundamentales, como en sitios de comercio electronico, foros, y sistemas de gestion de contenidos. MySQL es conocido por su rendimiento, fiabilidad, y facilidad de uso, ademas de ser de codigo abierto, lo que permite una amplia adopcion y contribucion de la comunidad.','./img/mysql.png',1,'2024-08-21 22:33:34');
INSERT INTO publicaciones (`id`,`titulo`,`contenido`,`img_url`,`autor_id`,`creado_en`) VALUES (6,'Bootstrap','Bootstrap es un framework de front-end de codigo abierto que facilita el desarrollo de sitios web y aplicaciones web responsivas y moviles. Fue desarrollado originalmente por Twitter y ha ganado popularidad por su simplicidad y eficiencia en la creacion de interfaces de usuario modernas y coherentes. Bootstrap proporciona una amplia coleccion de componentes predefinidos, como botones, formularios, menus de navegacion, y tablas, ademas de un potente sistema de grillas (grid) que permite organizar el contenido en una estructura flexible y adaptable a diferentes tamanos de pantalla.','./img/bootstrap.png',1,'2024-08-21 22:33:34');
INSERT INTO publicaciones (`id`,`titulo`,`contenido`,`img_url`,`autor_id`,`creado_en`) VALUES (7,'React.js','React.js es una biblioteca de JavaScript desarrollada por Facebook, utilizada para construir interfaces de usuario interactivas. React permite a los desarrolladores crear componentes reutilizables que manejan su propio estado, lo que facilita la creacion de aplicaciones complejas de manera eficiente y modular. Gracias a su enfoque declarativo y basado en componentes, React simplifica la gestion de vistas dinamicas en aplicaciones de una sola pagina (SPA). Tambien se destaca por su virtual DOM, que optimiza el rendimiento de las aplicaciones al minimizar la manipulacion directa del DOM real.','./img/react.png',1,'2024-08-21 22:33:34');
INSERT INTO publicaciones (`id`,`titulo`,`contenido`,`img_url`,`autor_id`,`creado_en`) VALUES (8,'Node.js','Node.js es un entorno de ejecucion para JavaScript que permite a los desarrolladores ejecutar codigo del lado del servidor. Basado en el motor V8 de Google Chrome, Node.js es conocido por su arquitectura asincrona y orientada a eventos, lo que lo hace ideal para aplicaciones escalables y de alto rendimiento, como servidores web, APIs y aplicaciones en tiempo real. Node.js se utiliza comunmente en conjunto con Express.js para construir aplicaciones web completas utilizando JavaScript tanto en el cliente como en el servidor.','./img/nodejs.png',1,'2024-08-21 22:33:34');
INSERT INTO publicaciones (`id`,`titulo`,`contenido`,`img_url`,`autor_id`,`creado_en`) VALUES (9,'Angular','Angular es un framework de desarrollo web de codigo abierto mantenido por Google, disenado para construir aplicaciones web dinamicas y de una sola pagina (SPA). Angular permite a los desarrolladores estructurar sus aplicaciones de manera modular utilizando componentes y servicios, ademas de proporcionar herramientas avanzadas como inyeccion de dependencias, enrutamiento y manejo de formularios. Con un enfoque basado en TypeScript, Angular es ideal para proyectos grandes y escalables.','./img/angular.png',1,'2024-08-21 22:33:34');
INSERT INTO publicaciones (`id`,`titulo`,`contenido`,`img_url`,`autor_id`,`creado_en`) VALUES (10,'Laravel','Laravel es un framework de PHP orientado a la creacion de aplicaciones web con una sintaxis elegante y expresiva. Es conocido por simplificar tareas comunes como enrutamiento, autenticacion, manejo de bases de datos y plantillas. Laravel sigue el patron de diseno MVC (Modelo-Vista-Controlador), lo que facilita la separacion logica del desarrollo y la gestion del flujo de la aplicacion. Incluye herramientas como Eloquent ORM para interactuar con bases de datos de manera fluida, y Blade como motor de plantillas.','./img/laravel.png',1,'2024-08-21 22:33:34');